site_name: Ephraim Designs
site_url: https://dev3l.github.io/ephraim-designs/
site_description: "Transforming spaces with faith-centered art."

theme:
  name: material
  palette:
    primary: "#002244" # Darker Blue for better contrast
    accent: "#CC9900" # Darker Gold for better contrast
    background: "#FFFFFF" # White background for maximum contrast
  font:
    text: "Open Sans, sans-serif" # Clean sans-serif for body text
    code: "Roboto Mono, monospace" # Modern monospace for code blocks
    headings: "Playfair Display, serif" # Elegant serif for headings
  fonts:
    text:
      family: "Open Sans"
      variants: ["300", "400", "600"]
    heading:
      family: "Playfair Display"
      variants: ["400", "700"]
    monospace:
      family: "Roboto Mono"
      variants: ["400"]
  favicon: "images/favicon.png"


nav:
  - Home: index.md

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
