# Site Information
site_name: Ephraim Designs
site_url: https://dev3l.github.io/ephraim-designs/
site_author: Justin Beall
site_description: "Infusing creativity with spirituality and passion, Ephraim Designs transforms spaces through custom murals, canvas art, live events, and community projects. Discover the dynamic artistry of Jason Rakich in Wooster, Ohio."

# Theme Configuration
theme:
  name: material
  palette:
    scheme: slate
    primary: teal

  font:
    text: Open Sans
    code: "Roboto Mono" # Monospace font for code blocks
  favicon: "images/favicon.png"
  logo: "images/logo.png"

# Navigation Structure
nav:
  - Home: index.md
  - About: about.md
  - Portfolio:
      - Murals: portfolio/murals.md
      - Paintings: portfolio/paintings.md
      - Live Art: portfolio/live-art.md
  - Services: services.md
  # - Community Engagement: community-engagement.md
  # - Pricing: pricing.md
  # - Events: events.md
  # - Blog:
  #     - Blog Home: blog/index.md
  # - Testimonials: testimonials.md
  # - Contact: contact.md

# Plugins
plugins:
  - search
  - macros
  - ultralytics:
      verbose: true
      enabled: true
      add_desc: true
      add_image: true
      add_keywords: true
      add_json_ld: true
      add_css: true
  - minify_html

# Markdown Extensions
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - footnotes

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - overrides/footer.js
