# Site Information
site_name: Ephraim Designs
site_url: https://ephraim-designs.com
site_author: Jason Rakich
site_description: "Transforming spaces with faith-centered art in Wooster, Ohio."

# Theme Configuration
theme:
  name: material
  palette:
    primary: "indigo" # Use a strong brand color
    accent: "amber" # Secondary color for highlights
  font:
    text: "Open Sans" # Readable sans-serif font for body
    code: "Roboto Mono" # Monospace font for code blocks
  features:
    - footer
  favicon: "images/favicon.png"
  logo: "images/logo-dark.png"

# Navigation Structure
nav:
  - Home: index.md
  - About: about.md
  - Portfolio:
      - Murals: portfolio/murals.md
      - Paintings: portfolio/paintings.md
      - Live Art: portfolio/live-art.md
  - Services: services.md
  - Community Engagement: community-engagement.md
  - Pricing: pricing.md
  - Events: events.md
  - Blog:
      - Blog Home: blog/index.md
  - Testimonials: testimonials.md
  - Contact: contact.md

# Plugins
plugins:
  - search
  - macros
  - ultralytics:
      verbose: true
      enabled: true
      default_image: "https://ephraim-designs.com/images/banner.png"
      add_desc: true
      add_image: true
      add_keywords: true
      add_json_ld: true
      add_css: true
  - minify_html

# Markdown Extensions
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - footnotes

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - overrides/footer.js

extra:
  generator: false
